export const ATTENDEES_REQUEST = 'ATTENDEES_REQUEST';
export const ATTENDEES_SUCCESS = 'ATTENDEES_SUCCESS';
export const ATTENDEES_ERROR = 'ATTENDEES_ERROR';
export const ATTENDEES_UPDATE = 'ATTENDEES_UPDATE';
